### PR TITLE
Added session joining functionality

### PR DESCRIPTION
**Pull request by LouisAsanaka**
Hey Tim! I really appreciate the work on adding group session hosting for the desktop Spotify client. I have gone ahead and added session joining as well. I've tested it a bit and it seems to work just fine. The only thing is that if the user is already in a session on their phone, this does not "join" / sync the session for them until they press "Create Session", which may be a bit misleading.

### CODE REVIEW

**Comment by t1mlange** [comment]
Hi,

thanks for the help! I will look into your changes in the following days.

> The only thing is that if the user is already in a session on their phone, this does not "join" / sync the session for them until they press "Create Session", which may be a bit misleading.

If Spotify can do it, we can do it too. I fired up my proxy setup again and looked out for it. There is a /current?local_device_id=xxx endpoint, which returns the following if a session exists:
```
{
    "timestamp": "XXX",
    "session_id": "XXX",
    "join_session_token": "XXX",
    "join_session_url": "XXX",
    "session_owner_id": "XXX",
    "session_members": [
        {
            "joined_timestamp": "XXX",
            "id": "XXX",
            "username": "XXX",
            "display_name": "Tim",
            "is_listening": true,
            "is_controlling": true
        }
    ],
    "join_session_uri": "XXX",
    "is_session_owner": true,
    "is_listening": true,
    "is_controlling": true,
    "initialSessionType": "REMOTE",
    "maxMemberCount": 8
}
```
and this if no group session is present:
```
{
    "timestamp": "XXX",
    "session_id": "XXX",
    "join_session_token": "XXX",
    "join_session_url": "XXX",
    "session_owner_id": "XXX",
    "session_members": [
        {
            "joined_timestamp": "XXX",
            "id": "XXX",
            "username": "XXX",
            "display_name": "Tim",
            "is_listening": true,
            "is_controlling": true
        }
    ],
    "join_session_uri": "XXX",
    "is_session_owner": true,
    "is_listening": true,
    "is_controlling": true,
    "initialSessionType": "IN_PERSON",
    "hostActiveDeviceId": "XXX",
    "maxMemberCount": 8
}
```
If you want to, you could query the current endpoint and look for `initialSessionType`. If it is REMOTE, use the response to fill the values.

**Comment by LouisAsanaka** [comment]
Looks good! I will try and incorporate that in the changes.

Also, the mobile client could join a session at any time without the desktop client knowing. Do you think this would be an endpoint that would be queried at an interval?

**Comment by t1mlange** [comment]
> Also, the mobile client could join a session at any time without the desktop client knowing. Do you think this would be an endpoint that would be queried at an interval?

Yeah. I think we should do the same as with the alive check where I query /info every 5 seconds to find out if the session got canceled. Additionally, it might be useful to do an additional request at startup.

**Comment by LouisAsanaka** [comment]
Changes have been implemented. ~~Not fully tested with other remote clients though, so this shouldn't be merged yet.~~

I also had to switch to another way of getting the local device ID, since the provided device_identifier from Spicetify (retrieved from [another Spotify endpoint here](https://github.com/spicetify/spicetify-cli/blob/e7ea852355d55eb153d3d8e7279e714a883d1c55/jsHelper/spicetifyWrapper.js#L188-L205)) seems to be very inconsistent (occasionally returns an empty string, as well as a plain wrong identifier). That said, the device identifier doesn't seem to be needed for some of the API calls that we make, but I kept them in to ensure future compatibility.

**Comment by t1mlange** [comment]
Hi,

I tested  it a bit and could not find any bugs, so I merged it now. Thanks for the help!

**Comment by LouisAsanaka** [comment]
Awesome! Appreciate your work as well.

**Pull request merged**
